apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-app-configs
data: 
  configs.yaml: |-
    user:
      host: "0.0.0.0"
      port: 8000

    db:
      driver: "postgres"
      host: "0.0.0.0"
      # host: "draft-postgres"
      port: "5432"
      user: "postgres"
      name: "postgres"
      password: "password"
      sslMode: "disable"

    cacheRedis:
      # host: "draft-redis"
      host: "0.0.0.0"
      port: "6379"
      password: ""
      dbNumber: 0
