apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-app-nginx-conf
data: 
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections  1024;
    }

    http {
        server {
            listen       80;
            location / {
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;

                proxy_pass http://127.0.0.1/8000;
            }
        }
    }