apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-gateway
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx-conf
            readOnly: true
            subPath: default.conf          
          - mountPath: /etc/nginx/conf.d/upstream.conf
            name: nginx-conf
            readOnly: true
            subPath: upstream.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: backend-app-nginx-conf
