apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "draft-backend.fullname" . }}-configs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "draft-backend.labels" . | nindent 4 }}
data: 
  configs.yaml: |-
    user:
      host: "0.0.0.0"
      port: 8000

    db:
      driver: "postgres"
      host: "backend-db"
      port: "5432"
      user: "postgres"
      name: "postgres"
      password: "password"
      sslMode: "disable"

    cacheRedis:
      host: "backend-cache"
      port: "6379"
      password: ""
      dbNumber: 0
