apiVersion: v1
kind: Service
metadata:
  name: {{ include "draft-backend.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "draft-backend.labels" . | nindent 4 }}
spec:
  selector:
    app: backend-app
  ports:
  - name: api-v1
    port: 8000
    protocol: TCP
    targetPort: 8000
  type: ClusterIP