apiVersion: v1
kind: Service
metadata:
  name: {{ include "draft-backend.fullname" . }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "draft-backend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "draft-backend.cacheSelectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 6379
  type: ClusterIP
