kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "draft-backend.fullname" . }}-db-volume
  # namespace: {{ .Release.Namespace }}
  labels:
    {{- include "draft-backend.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/draft/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "draft-backend.fullname" . }}-claim
  # namespace: {{ .Release.Namespace }}
  labels:
    {{- include "draft-backend.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
