apiVersion: v1
kind: Service
metadata:
  name: {{ include "draft-backend.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "draft-backend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "draft-backend.dbSelectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 5432
  type: LoadBalancer