apiVersion: v1
kind: Service
metadata:
  name: {{ include "draft-backend.fullname" . }}-nginx-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "draft-backend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "draft-backend.gatewaySelectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
