apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "draft-backend.fullname" . }}-nginx-conf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "draft-backend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  draft.com;


        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /api/ {
          proxy_pass http://userapi/;
          proxy_set_header Host $http_host;
        }
    }
  upstream.conf: |
    upstream  userapi {
      server  {{ include "draft-backend.fullname" . }}-app:8000;
    }
